//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Snezhko_eshhe
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Запись.
    /// </summary>
    // *** Start programmer edit section *** (Запись CustomAttributes)

    // *** End programmer edit section *** (Запись CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаписьE", new string[] {
            "КодЗаписи as \'Код записи\'",
            "Дата as \'Дата\'",
            "Время as \'Время\'",
            "Комментарий as \'Комментарий\'",
            "Сумма as \'Сумма\'",
            "Клиент as \'Клиент\'",
            "Клиент.Фамилия as \'Фамилия\'",
            "Бокс as \'Бокс\'",
            "Бокс.НомерБокса as \'Номер бокса\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.Фамилия as \'Фамилия\'"}, Hidden=new string[] {
            "Клиент.Фамилия",
            "Бокс.НомерБокса",
            "Сотрудники.Фамилия"})]
    [AssociatedDetailViewAttribute("ЗаписьE", "СоставЗаписи", "СоставЗаписиE", true, "", "Состав записи", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЗаписьE", "Клиент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [MasterViewDefineAttribute("ЗаписьE", "Бокс", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерБокса")]
    [MasterViewDefineAttribute("ЗаписьE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [View("ЗаписьL", new string[] {
            "КодЗаписи as \'Код записи\'",
            "Дата as \'Дата\'",
            "Время as \'Время\'",
            "Комментарий as \'Комментарий\'",
            "Сумма as \'Сумма\'",
            "Клиент.Фамилия as \'Фамилия\'",
            "Бокс.НомерБокса as \'Номер бокса\'",
            "Сотрудники.Фамилия as \'Фамилия\'"})]
    public class Запись : IIS.Snezhko_eshhe.РегистЗаписи
    {
        
        private string fКомментарий;
        
        private IIS.Snezhko_eshhe.Клиент fКлиент;
        
        private IIS.Snezhko_eshhe.Бокс fБокс;
        
        private IIS.Snezhko_eshhe.Сотрудники fСотрудники;
        
        private IIS.Snezhko_eshhe.DetailArrayOfСоставЗаписи fСоставЗаписи;
        
        // *** Start programmer edit section *** (Запись CustomMembers)

        // *** End programmer edit section *** (Запись CustomMembers)

        
        /// <summary>
        /// Время.
        /// </summary>
        // *** Start programmer edit section *** (Запись.Время CustomAttributes)

        // *** End programmer edit section *** (Запись.Время CustomAttributes)
        [StrLen(255)]
        public override string Время
        {
            get
            {
                // *** Start programmer edit section *** (Запись.Время Get start)

                // *** End programmer edit section *** (Запись.Время Get start)
                string result = base.Время;
                // *** Start programmer edit section *** (Запись.Время Get end)

                // *** End programmer edit section *** (Запись.Время Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.Время Set start)

                // *** End programmer edit section *** (Запись.Время Set start)
                base.Время = value;
                // *** Start programmer edit section *** (Запись.Время Set end)

                // *** End programmer edit section *** (Запись.Время Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Запись.Дата CustomAttributes)

        // *** End programmer edit section *** (Запись.Дата CustomAttributes)
        public override System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Запись.Дата Get start)

                // *** End programmer edit section *** (Запись.Дата Get start)
                System.DateTime result = base.Дата;
                // *** Start programmer edit section *** (Запись.Дата Get end)

                // *** End programmer edit section *** (Запись.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.Дата Set start)

                // *** End programmer edit section *** (Запись.Дата Set start)
                base.Дата = value;
                // *** Start programmer edit section *** (Запись.Дата Set end)

                // *** End programmer edit section *** (Запись.Дата Set end)
            }
        }
        
        /// <summary>
        /// КодЗаписи.
        /// </summary>
        // *** Start programmer edit section *** (Запись.КодЗаписи CustomAttributes)

        // *** End programmer edit section *** (Запись.КодЗаписи CustomAttributes)
        public override int КодЗаписи
        {
            get
            {
                // *** Start programmer edit section *** (Запись.КодЗаписи Get start)

                // *** End programmer edit section *** (Запись.КодЗаписи Get start)
                int result = base.КодЗаписи;
                // *** Start programmer edit section *** (Запись.КодЗаписи Get end)

                // *** End programmer edit section *** (Запись.КодЗаписи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.КодЗаписи Set start)

                // *** End programmer edit section *** (Запись.КодЗаписи Set start)
                base.КодЗаписи = value;
                // *** Start programmer edit section *** (Запись.КодЗаписи Set end)

                // *** End programmer edit section *** (Запись.КодЗаписи Set end)
            }
        }
        
        /// <summary>
        /// Комментарий.
        /// </summary>
        // *** Start programmer edit section *** (Запись.Комментарий CustomAttributes)

        // *** End programmer edit section *** (Запись.Комментарий CustomAttributes)
        [StrLen(255)]
        public virtual string Комментарий
        {
            get
            {
                // *** Start programmer edit section *** (Запись.Комментарий Get start)

                // *** End programmer edit section *** (Запись.Комментарий Get start)
                string result = this.fКомментарий;
                // *** Start programmer edit section *** (Запись.Комментарий Get end)

                // *** End programmer edit section *** (Запись.Комментарий Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.Комментарий Set start)

                // *** End programmer edit section *** (Запись.Комментарий Set start)
                this.fКомментарий = value;
                // *** Start programmer edit section *** (Запись.Комментарий Set end)

                // *** End programmer edit section *** (Запись.Комментарий Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (Запись.Сумма CustomAttributes)

        // *** End programmer edit section *** (Запись.Сумма CustomAttributes)
        public override double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (Запись.Сумма Get start)

                // *** End programmer edit section *** (Запись.Сумма Get start)
                double result = base.Сумма;
                // *** Start programmer edit section *** (Запись.Сумма Get end)

                // *** End programmer edit section *** (Запись.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.Сумма Set start)

                // *** End programmer edit section *** (Запись.Сумма Set start)
                base.Сумма = value;
                // *** Start programmer edit section *** (Запись.Сумма Set end)

                // *** End programmer edit section *** (Запись.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Запись.
        /// </summary>
        // *** Start programmer edit section *** (Запись.Бокс CustomAttributes)

        // *** End programmer edit section *** (Запись.Бокс CustomAttributes)
        [PropertyStorage(new string[] {
                "Бокс"})]
        [NotNull()]
        public virtual IIS.Snezhko_eshhe.Бокс Бокс
        {
            get
            {
                // *** Start programmer edit section *** (Запись.Бокс Get start)

                // *** End programmer edit section *** (Запись.Бокс Get start)
                IIS.Snezhko_eshhe.Бокс result = this.fБокс;
                // *** Start programmer edit section *** (Запись.Бокс Get end)

                // *** End programmer edit section *** (Запись.Бокс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.Бокс Set start)

                // *** End programmer edit section *** (Запись.Бокс Set start)
                this.fБокс = value;
                // *** Start programmer edit section *** (Запись.Бокс Set end)

                // *** End programmer edit section *** (Запись.Бокс Set end)
            }
        }
        
        /// <summary>
        /// Запись.
        /// </summary>
        // *** Start programmer edit section *** (Запись.Клиент CustomAttributes)

        // *** End programmer edit section *** (Запись.Клиент CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент"})]
        [NotNull()]
        public virtual IIS.Snezhko_eshhe.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (Запись.Клиент Get start)

                // *** End programmer edit section *** (Запись.Клиент Get start)
                IIS.Snezhko_eshhe.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (Запись.Клиент Get end)

                // *** End programmer edit section *** (Запись.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.Клиент Set start)

                // *** End programmer edit section *** (Запись.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (Запись.Клиент Set end)

                // *** End programmer edit section *** (Запись.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Запись.
        /// </summary>
        // *** Start programmer edit section *** (Запись.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (Запись.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Snezhko_eshhe.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (Запись.Сотрудники Get start)

                // *** End programmer edit section *** (Запись.Сотрудники Get start)
                IIS.Snezhko_eshhe.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (Запись.Сотрудники Get end)

                // *** End programmer edit section *** (Запись.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.Сотрудники Set start)

                // *** End programmer edit section *** (Запись.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (Запись.Сотрудники Set end)

                // *** End programmer edit section *** (Запись.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Запись.
        /// </summary>
        // *** Start programmer edit section *** (Запись.СоставЗаписи CustomAttributes)

        // *** End programmer edit section *** (Запись.СоставЗаписи CustomAttributes)
        public virtual IIS.Snezhko_eshhe.DetailArrayOfСоставЗаписи СоставЗаписи
        {
            get
            {
                // *** Start programmer edit section *** (Запись.СоставЗаписи Get start)

                // *** End programmer edit section *** (Запись.СоставЗаписи Get start)
                if ((this.fСоставЗаписи == null))
                {
                    this.fСоставЗаписи = new IIS.Snezhko_eshhe.DetailArrayOfСоставЗаписи(this);
                }
                IIS.Snezhko_eshhe.DetailArrayOfСоставЗаписи result = this.fСоставЗаписи;
                // *** Start programmer edit section *** (Запись.СоставЗаписи Get end)

                // *** End programmer edit section *** (Запись.СоставЗаписи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.СоставЗаписи Set start)

                // *** End programmer edit section *** (Запись.СоставЗаписи Set start)
                this.fСоставЗаписи = value;
                // *** Start programmer edit section *** (Запись.СоставЗаписи Set end)

                // *** End programmer edit section *** (Запись.СоставЗаписи Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаписьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьE", typeof(IIS.Snezhko_eshhe.Запись));
                }
            }
            
            /// <summary>
            /// "ЗаписьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьL", typeof(IIS.Snezhko_eshhe.Запись));
                }
            }
        }
    }
}
