//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Snezhko_eshhe
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Материалы.
    /// </summary>
    // *** Start programmer edit section *** (Материалы CustomAttributes)

    // *** End programmer edit section *** (Материалы CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МатериалыE", new string[] {
            "КодДетали as \'Код материала\'",
            "Наименование as \'Наименование\'",
            "Производитель as \'Производитель\'",
            "Производитель.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Производитель.Наименование"})]
    [MasterViewDefineAttribute("МатериалыE", "Производитель", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("МатериалыL", new string[] {
            "КодДетали as \'Код материала\'",
            "Наименование as \'Наименование\'",
            "Производитель.Наименование as \'Наименование\'"})]
    public class Материалы : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодДетали;
        
        private string fНаименование;
        
        private IIS.Snezhko_eshhe.Производитель fПроизводитель;
        
        // *** Start programmer edit section *** (Материалы CustomMembers)

        // *** End programmer edit section *** (Материалы CustomMembers)

        
        /// <summary>
        /// КодДетали.
        /// </summary>
        // *** Start programmer edit section *** (Материалы.КодДетали CustomAttributes)

        // *** End programmer edit section *** (Материалы.КодДетали CustomAttributes)
        public virtual int КодДетали
        {
            get
            {
                // *** Start programmer edit section *** (Материалы.КодДетали Get start)

                // *** End programmer edit section *** (Материалы.КодДетали Get start)
                int result = this.fКодДетали;
                // *** Start programmer edit section *** (Материалы.КодДетали Get end)

                // *** End programmer edit section *** (Материалы.КодДетали Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Материалы.КодДетали Set start)

                // *** End programmer edit section *** (Материалы.КодДетали Set start)
                this.fКодДетали = value;
                // *** Start programmer edit section *** (Материалы.КодДетали Set end)

                // *** End programmer edit section *** (Материалы.КодДетали Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Материалы.Наименование CustomAttributes)

        // *** End programmer edit section *** (Материалы.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Материалы.Наименование Get start)

                // *** End programmer edit section *** (Материалы.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Материалы.Наименование Get end)

                // *** End programmer edit section *** (Материалы.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Материалы.Наименование Set start)

                // *** End programmer edit section *** (Материалы.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Материалы.Наименование Set end)

                // *** End programmer edit section *** (Материалы.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Материалы.
        /// </summary>
        // *** Start programmer edit section *** (Материалы.Производитель CustomAttributes)

        // *** End programmer edit section *** (Материалы.Производитель CustomAttributes)
        [PropertyStorage(new string[] {
                "Производитель"})]
        [NotNull()]
        public virtual IIS.Snezhko_eshhe.Производитель Производитель
        {
            get
            {
                // *** Start programmer edit section *** (Материалы.Производитель Get start)

                // *** End programmer edit section *** (Материалы.Производитель Get start)
                IIS.Snezhko_eshhe.Производитель result = this.fПроизводитель;
                // *** Start programmer edit section *** (Материалы.Производитель Get end)

                // *** End programmer edit section *** (Материалы.Производитель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Материалы.Производитель Set start)

                // *** End programmer edit section *** (Материалы.Производитель Set start)
                this.fПроизводитель = value;
                // *** Start programmer edit section *** (Материалы.Производитель Set end)

                // *** End programmer edit section *** (Материалы.Производитель Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МатериалыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МатериалыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МатериалыE", typeof(IIS.Snezhko_eshhe.Материалы));
                }
            }
            
            /// <summary>
            /// "МатериалыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МатериалыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МатериалыL", typeof(IIS.Snezhko_eshhe.Материалы));
                }
            }
        }
    }
}
