//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Snezhko_eshhe
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состав записи.
    /// </summary>
    // *** Start programmer edit section *** (СоставЗаписи CustomAttributes)

    // *** End programmer edit section *** (СоставЗаписи CustomAttributes)
    [AutoAltered()]
    [Caption("Состав записи")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СоставЗаписиE", new string[] {
            "Услуга as \'Услуга\'",
            "Услуга.Наименование as \'Наименование\'",
            "Услуга.Цена as \'Цена\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.Фамилия as \'Фамилия\'"}, Hidden=new string[] {
            "Услуга.Наименование",
            "Сотрудники.Фамилия"})]
    [MasterViewDefineAttribute("СоставЗаписиE", "Услуга", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("СоставЗаписиE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    public class СоставЗаписи : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Snezhko_eshhe.Услуга fУслуга;
        
        private IIS.Snezhko_eshhe.Сотрудники fСотрудники;
        
        private IIS.Snezhko_eshhe.Запись fЗапись;
        
        // *** Start programmer edit section *** (СоставЗаписи CustomMembers)

        // *** End programmer edit section *** (СоставЗаписи CustomMembers)

        
        /// <summary>
        /// Состав записи.
        /// </summary>
        // *** Start programmer edit section *** (СоставЗаписи.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (СоставЗаписи.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Snezhko_eshhe.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (СоставЗаписи.Сотрудники Get start)

                // *** End programmer edit section *** (СоставЗаписи.Сотрудники Get start)
                IIS.Snezhko_eshhe.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (СоставЗаписи.Сотрудники Get end)

                // *** End programmer edit section *** (СоставЗаписи.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставЗаписи.Сотрудники Set start)

                // *** End programmer edit section *** (СоставЗаписи.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (СоставЗаписи.Сотрудники Set end)

                // *** End programmer edit section *** (СоставЗаписи.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Состав записи.
        /// </summary>
        // *** Start programmer edit section *** (СоставЗаписи.Услуга CustomAttributes)

        // *** End programmer edit section *** (СоставЗаписи.Услуга CustomAttributes)
        [PropertyStorage(new string[] {
                "Услуга"})]
        [NotNull()]
        public virtual IIS.Snezhko_eshhe.Услуга Услуга
        {
            get
            {
                // *** Start programmer edit section *** (СоставЗаписи.Услуга Get start)

                // *** End programmer edit section *** (СоставЗаписи.Услуга Get start)
                IIS.Snezhko_eshhe.Услуга result = this.fУслуга;
                // *** Start programmer edit section *** (СоставЗаписи.Услуга Get end)

                // *** End programmer edit section *** (СоставЗаписи.Услуга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставЗаписи.Услуга Set start)

                // *** End programmer edit section *** (СоставЗаписи.Услуга Set start)
                this.fУслуга = value;
                // *** Start programmer edit section *** (СоставЗаписи.Услуга Set end)

                // *** End programmer edit section *** (СоставЗаписи.Услуга Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Snezhko_eshhe.Запись.
        /// </summary>
        // *** Start programmer edit section *** (СоставЗаписи.Запись CustomAttributes)

        // *** End programmer edit section *** (СоставЗаписи.Запись CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Запись"})]
        public virtual IIS.Snezhko_eshhe.Запись Запись
        {
            get
            {
                // *** Start programmer edit section *** (СоставЗаписи.Запись Get start)

                // *** End programmer edit section *** (СоставЗаписи.Запись Get start)
                IIS.Snezhko_eshhe.Запись result = this.fЗапись;
                // *** Start programmer edit section *** (СоставЗаписи.Запись Get end)

                // *** End programmer edit section *** (СоставЗаписи.Запись Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставЗаписи.Запись Set start)

                // *** End programmer edit section *** (СоставЗаписи.Запись Set start)
                this.fЗапись = value;
                // *** Start programmer edit section *** (СоставЗаписи.Запись Set end)

                // *** End programmer edit section *** (СоставЗаписи.Запись Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СоставЗаписиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СоставЗаписиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СоставЗаписиE", typeof(IIS.Snezhko_eshhe.СоставЗаписи));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of СоставЗаписи.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСоставЗаписи CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСоставЗаписи CustomAttributes)
    public class DetailArrayOfСоставЗаписи : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Snezhko_eshhe.DetailArrayOfСоставЗаписи members)

        // *** End programmer edit section *** (IIS.Snezhko_eshhe.DetailArrayOfСоставЗаписи members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type СоставЗаписи by index.
        /// </summary>
        /// <summary>
        /// Adds object with type СоставЗаписи.
        /// </summary>
        public DetailArrayOfСоставЗаписи(IIS.Snezhko_eshhe.Запись fЗапись) : 
                base(typeof(СоставЗаписи), ((ICSSoft.STORMNET.DataObject)(fЗапись)))
        {
        }
        
        public IIS.Snezhko_eshhe.СоставЗаписи this[int index]
        {
            get
            {
                return ((IIS.Snezhko_eshhe.СоставЗаписи)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Snezhko_eshhe.СоставЗаписи dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
