//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Snezhko_eshhe
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип оплат.
    /// </summary>
    // *** Start programmer edit section *** (ТипОплат CustomAttributes)

    // *** End programmer edit section *** (ТипОплат CustomAttributes)
    public enum ТипОплат
    {
        
        // *** Start programmer edit section *** (ТипОплат.1 CustomAttributes)

        // *** End programmer edit section *** (ТипОплат.1 CustomAttributes)
        [Caption("Безналичный")]
        1,
        
        // *** Start programmer edit section *** (ТипОплат.2 CustomAttributes)

        // *** End programmer edit section *** (ТипОплат.2 CustomAttributes)
        [Caption("Наличный")]
        2,
        
        // *** Start programmer edit section *** (ТипОплат.3 CustomAttributes)

        // *** End programmer edit section *** (ТипОплат.3 CustomAttributes)
        [Caption("Переводом")]
        3,
        
        // *** Start programmer edit section *** (ТипОплат.4 CustomAttributes)

        // *** End programmer edit section *** (ТипОплат.4 CustomAttributes)
        [Caption("СБП")]
        4,
    }
}
